# Generated by Django 5.0.6 on 2024-05-31 16:56

import django.db.models.deletion
import galleries.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=70, verbose_name="Name")),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=3000, verbose_name="Description"
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=70)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="galleries.gallery",
                        verbose_name="Parent gallery",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "galleries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=galleries.models.photo_path,
                        validators=[galleries.models.check_image_size],
                        verbose_name="Photo",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, upload_to=galleries.models.thumbnail_path
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=70, verbose_name="Name"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=3000, verbose_name="Description"
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=70)),
                (
                    "date",
                    models.DateField(
                        help_text="Click on the month name or the year to change them quickly",
                        verbose_name="Date",
                    ),
                ),
                (
                    "gallery",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="galleries.gallery",
                        verbose_name="Gallery",
                    ),
                ),
            ],
            options={
                "ordering": ["gallery", "date", "name"],
            },
        ),
        migrations.AddField(
            model_name="gallery",
            name="cover",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="cover_of",
                to="galleries.photo",
                verbose_name="Cover Photo",
            ),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                fields=["gallery", "date", "name"],
                name="galleries_p_gallery_974a59_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="photo",
            constraint=models.UniqueConstraint(
                fields=("slug", "gallery"),
                name="slugs must be unique inside their gallery",
            ),
        ),
        migrations.AddIndex(
            model_name="gallery",
            index=models.Index(
                fields=["parent", "name"], name="galleries_g_parent__d0c5e7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="gallery",
            constraint=models.UniqueConstraint(
                fields=("slug", "parent"),
                name="slugs must be unique inside a parent gallery",
            ),
        ),
    ]
