# Generated by Django 5.0.2 on 2024-04-18 07:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='Description')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='galleries.gallery', verbose_name='Parent gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='galleries', verbose_name='Photo')),
                ('name', models.CharField(max_length=70, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='Description')),
                ('date', models.DateField(default=datetime.datetime(2024, 4, 18, 7, 21, 50, 154315, tzinfo=datetime.timezone.utc), verbose_name='Date')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleries.gallery', verbose_name='Gallery')),
            ],
        ),
        migrations.AddField(
            model_name='gallery',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cover_of', to='galleries.photo', verbose_name='Cover Photo'),
        ),
    ]
