# Generated by Django 5.0.2 on 2024-04-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_alter_photo_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['parent', 'name'], 'verbose_name_plural': 'galleries'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['gallery', 'date', 'name']},
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['parent', 'name'], name='galleries_g_parent__d0c5e7_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['gallery', 'date', 'name'], name='galleries_p_gallery_974a59_idx'),
        ),
    ]
