# Generated by Django 5.2 on 2025-05-24 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("galleries", "0003_photo_image_height_photo_image_width_and_more"),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.AddField(
      model_name="gallery",
      name="owner",
      field=models.ForeignKey(
        blank=True,
        null=True,
        on_delete=django.db.models.deletion.CASCADE,
        to=settings.AUTH_USER_MODEL,
        verbose_name="Owner",
      ),
    ),
    migrations.AddField(
      model_name="photo",
      name="uploaded_by",
      field=models.ForeignKey(
        blank=True,
        null=True,
        on_delete=django.db.models.deletion.CASCADE,
        to=settings.AUTH_USER_MODEL,
        verbose_name="Uploaded by",
      ),
    ),
  ]
