# Generated by Django 5.0.2 on 2024-04-18 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0003_alter_gallery_options_alter_photo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['name'], 'verbose_name_plural': 'galleries'},
        ),
    ]
