# Generated by Django 5.2.7 on 2025-11-02 09:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galleries", "0004_gallery_owner_photo_uploaded_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="photo",
            name="galleries_p_gallery_974a59_idx",
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                fields=["gallery"], name="galleries_p_gallery_226659_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(fields=["name"], name="galleries_p_name_7dd314_idx"),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                fields=["gallery", "id"], name="galleries_p_gallery_8b7786_idx"
            ),
        ),
    ]
