# Generated by Django 5.0.2 on 2024-04-18 18:05

import galleries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0004_alter_gallery_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(default='slug1', max_length=70, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='slug',
            field=models.SlugField(default='slug2', max_length=70, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(default=123, upload_to=galleries.models.thumbnail_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=galleries.models.photo_path, verbose_name='Photo'),
        ),
    ]
