# Generated by Django 5.0.2 on 2024-04-19 09:10

import django.db.models.deletion
import galleries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0005_gallery_slug_photo_slug_photo_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='galleries.gallery', verbose_name='Parent gallery'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(blank=True, max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='slug',
            field=models.SlugField(blank=True, max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=galleries.models.thumbnail_path),
        ),
    ]
