# Generated by Django 6.0 on 2026-02-25 19:06

import galleries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0005_remove_photo_galleries_p_gallery_974a59_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image_width',
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.FileField(max_length=1000, upload_to=galleries.models.photo_path, validators=[galleries.models.check_image_size], verbose_name='Photo or Video'),
        ),
    ]
