# Generated by Django 6.0.8 on 2026-08-08 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_default_tenant(apps, schema_editor):
  from django.conf import settings

  Tenant = apps.get_model("tenants", "Tenant")
  Gallery = apps.get_model("galleries", "Gallery")
  Photo = apps.get_model("galleries", "Photo")
  db = schema_editor.connection.alias
  default = Tenant.objects.using(db).get(slug=settings.DEFAULT_TENANT_SLUG)
  # Legacy galleries/photos land on the default tenant.
  Gallery.objects.using(db).filter(tenant__isnull=True).update(tenant=default)
  Photo.objects.using(db).filter(tenant__isnull=True).update(tenant=default)


def unassign_tenant(apps, schema_editor):
  Gallery = apps.get_model("galleries", "Gallery")
  Photo = apps.get_model("galleries", "Photo")
  db = schema_editor.connection.alias
  Gallery.objects.using(db).update(tenant=None)
  Photo.objects.using(db).update(tenant=None)


class Migration(migrations.Migration):
  dependencies = [
    ("galleries", "0006_video_support"),
    ("tenants", "0002_seed_tenants"),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.RemoveConstraint(
      model_name="gallery",
      name="slugs must be unique inside a parent gallery",
    ),
    migrations.RemoveConstraint(
      model_name="photo",
      name="slugs must be unique inside their gallery",
    ),
    migrations.RemoveIndex(
      model_name="gallery",
      name="galleries_g_parent__d0c5e7_idx",
    ),
    migrations.RemoveIndex(
      model_name="photo",
      name="galleries_p_gallery_226659_idx",
    ),
    migrations.RemoveIndex(
      model_name="photo",
      name="galleries_p_name_7dd314_idx",
    ),
    migrations.RemoveIndex(
      model_name="photo",
      name="galleries_p_gallery_8b7786_idx",
    ),
    migrations.AddField(
      model_name="gallery",
      name="tenant",
      field=models.ForeignKey(
        editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
      ),
    ),
    migrations.AddField(
      model_name="photo",
      name="tenant",
      field=models.ForeignKey(
        editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
      ),
    ),
    # Backfill the (temporarily nullable) tenant before constraints/non-null.
    migrations.RunPython(assign_default_tenant, reverse_code=unassign_tenant),
    migrations.AddIndex(
      model_name="gallery",
      index=models.Index(fields=["tenant", "slug"], name="galleries_g_tenant__148567_idx"),
    ),
    migrations.AddIndex(
      model_name="gallery",
      index=models.Index(fields=["tenant", "parent", "name"], name="galleries_g_tenant__78cd75_idx"),
    ),
    migrations.AddIndex(
      model_name="photo",
      index=models.Index(fields=["tenant", "gallery"], name="galleries_p_tenant__d94506_idx"),
    ),
    migrations.AddIndex(
      model_name="photo",
      index=models.Index(fields=["tenant", "name"], name="galleries_p_tenant__970d05_idx"),
    ),
    migrations.AddIndex(
      model_name="photo",
      index=models.Index(fields=["tenant", "gallery", "id"], name="galleries_p_tenant__bef816_idx"),
    ),
    migrations.AddConstraint(
      model_name="gallery",
      constraint=models.UniqueConstraint(
        fields=("tenant", "slug", "parent"), name="slugs must be unique inside a parent gallery"
      ),
    ),
    migrations.AddConstraint(
      model_name="photo",
      constraint=models.UniqueConstraint(
        fields=("tenant", "slug", "gallery"), name="slugs must be unique inside their gallery"
      ),
    ),
    migrations.AlterField(
      model_name="gallery",
      name="tenant",
      field=models.ForeignKey(
        editable=False, on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
      ),
    ),
    migrations.AlterField(
      model_name="photo",
      name="tenant",
      field=models.ForeignKey(
        editable=False, on_delete=django.db.models.deletion.CASCADE, related_name="+", to="tenants.tenant"
      ),
    ),
  ]
