# Generated by Django 5.0.2 on 2024-04-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0007_alter_photo_gallery_alter_photo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(blank=True, max_length=70),
        ),
    ]
