# Generated by Django 5.0.2 on 2024-04-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0009_alter_photo_slug_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='photo',
            name='slugs must be unique inside their gallery',
        ),
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.UniqueConstraint(fields=('slug', 'gallery'), name='slugs must be unique inside their gallery'),
        ),
    ]
