# Generated by Django 5.0.2 on 2024-04-22 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0010_remove_photo_slugs_must_be_unique_inside_their_gallery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='galleries.gallery', verbose_name='Parent gallery'),
        ),
        migrations.AddConstraint(
            model_name='gallery',
            constraint=models.UniqueConstraint(fields=('slug', 'parent'), name='slugs must be unique inside a parent gallery'),
        ),
    ]
