# Generated by Django 5.0.2 on 2024-04-23 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0011_alter_gallery_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='cover',
            field=models.ForeignKey(blank=True, default='default_gallery.jpg', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cover_of', to='galleries.photo', verbose_name='Cover Photo'),
        ),
    ]
