# Generated by Django 5.0.2 on 2024-04-23 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0012_alter_gallery_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cover_of', to='galleries.photo', verbose_name='Cover Photo'),
        ),
    ]
