# Generated by Django 5.0.2 on 2024-05-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0013_alter_gallery_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date',
            field=models.DateField(help_text='Click on the month name or the year to change them quickly', verbose_name='Date'),
        ),
    ]
