# Generated by Django 5.0.6 on 2024-05-18 16:02

import galleries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0015_alter_gallery_description_alter_photo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=galleries.models.photo_path, validators=[galleries.models.check_image_size], verbose_name='Photo'),
        ),
    ]
