# Generated by Django 5.0.2 on 2024-03-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CousinsMatterParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_title', models.CharField(default='Cousins Matter!', max_length=128, verbose_name='Home title')),
                ('home_content', models.TextField(verbose_name='Home content')),
                ('home_logo', models.ImageField(default='static/images/cousinsmatter.jpg', upload_to='', verbose_name='Home logo')),
            ],
        ),
    ]
