# Generated by Django 5.0.2 on 2024-02-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cousinsmatterparameters',
            name='home_title',
            field=models.CharField(default='Cousins Matter!', max_length=128),
        ),
    ]
