# Generated by Django 5.0.2 on 2024-04-09 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cm_main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CousinsMatterParameters',
        ),
    ]
