# run with: docker-compose -f docker-compose.debug.yml up
# then attach in vscode using the "Python: Remote Attach" debug config
services:
  cousinsmatter:
    image: ${COUSINS_MATTER_IMAGE:-cousins-matter}
    container_name: cousins-matter-debug
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./data:/app/data
      - ./media:/app/media
      - ./.env:/app/.env
    ports:
      - "$DOCKER_PORT:8000"
      - 5678:5678  # for debugpy
    command: ["sh", "-c", "pip install debugpy -t /tmp && python -Xfrozen_modules=off /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000 --nothreading --noreload"]
