services:
  postgres:
    image: postgres:16-alpine
    container_name: cousins-matter-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  pgloader:
    image: dimitri/pgloader:latest
    container_name: cousins-matter-pgloader
    depends_on: ["postgres"]
    entrypoint: ["pgloader"]
    command: ["sqlite:///data/db.sqlite3", "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"]
    volumes:
      - ./data:/data