# Generated by Django 5.0.6 on 2024-05-19 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscontent',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='newscontent',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newscontent'),
        ),
    ]
