# Generated by Django 5.0.6 on 2024-05-19 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newscontent_options_alter_newscontent_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscontent',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.news'),
        ),
    ]
