# Generated by Django 5.2 on 2025-04-16 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_choiceanswer_answer_question_possible_choices_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choiceanswer',
            options={'verbose_name': 'choice answer', 'verbose_name_plural': 'choice answers'},
        ),
        migrations.AlterModelOptions(
            name='datetimeanswer',
            options={'verbose_name': 'date answer', 'verbose_name_plural': 'date answers'},
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['pub_date'], 'verbose_name': 'poll', 'verbose_name_plural': 'polls'},
        ),
        migrations.AlterModelOptions(
            name='pollanswer',
            options={'verbose_name': 'poll answer', 'verbose_name_plural': 'poll answers'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id'], 'verbose_name': 'question', 'verbose_name_plural': 'questions'},
        ),
        migrations.AlterModelOptions(
            name='textanswer',
            options={'verbose_name': 'text answer', 'verbose_name_plural': 'text answers'},
        ),
        migrations.AlterModelOptions(
            name='yesnoanswer',
            options={'verbose_name': 'yes/no answer', 'verbose_name_plural': 'yes/no answers'},
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('YN', 'Yes/No'), ('SC', 'Single Choice'), ('MC', 'Multiple Choices'), ('OT', 'Open Text'), ('DT', 'Date'), ('EV', 'Event')], default='YN', max_length=2, verbose_name='Question Type'),
        ),
        migrations.CreateModel(
            name='EventAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, default='', max_length=100, verbose_name='choice')),
                ('poll_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pollanswer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_%(class)s', to='polls.question')),
            ],
            options={
                'verbose_name': 'choice answer',
                'verbose_name_plural': 'choice answers',
            },
        ),
        migrations.CreateModel(
            name='MultiChoiceAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField(blank=True, default=list, verbose_name='choices')),
                ('poll_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pollanswer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_%(class)s', to='polls.question')),
            ],
            options={
                'verbose_name': 'multiple choice answer',
                'verbose_name_plural': 'multiple choice answers',
            },
        ),
    ]
