# Generated by Django 5.2 on 2025-04-17 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_choiceanswer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiEventAnswer',
            fields=[
                ('multichoiceanswer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.multichoiceanswer')),
            ],
            options={
                'verbose_name': 'multiple event answer',
                'verbose_name_plural': 'multiple event answers',
            },
            bases=('polls.multichoiceanswer',),
        ),
        migrations.CreateModel(
            name='SingleEventAnswer',
            fields=[
                ('choiceanswer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.choiceanswer')),
            ],
            options={
                'verbose_name': 'single event answer',
                'verbose_name_plural': 'single event answers',
            },
            bases=('polls.choiceanswer',),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('YN', 'Yes/No'), ('SC', 'Single Choice'), ('MC', 'Multiple Choices'), ('OT', 'Open Text'), ('DT', 'Date'), ('ME', 'Multiple Choices Event'), ('SE', 'Single Choice Event')], default='YN', max_length=2, verbose_name='Question Type'),
        ),
        migrations.DeleteModel(
            name='EventAnswer',
        ),
    ]
