# Generated by Django 5.2 on 2025-04-17 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_multieventanswer_singleeventanswer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPlanner',
            fields=[
                ('poll_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.poll')),
                ('location', models.CharField(blank=True, default='', max_length=250, verbose_name='location')),
                ('chosen_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'event planner',
                'verbose_name_plural': 'event planners',
            },
            bases=('polls.poll',),
        ),
        migrations.CreateModel(
            name='MultiEventPlanner',
            fields=[
                ('eventplanner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.eventplanner')),
            ],
            options={
                'verbose_name': 'multiple event planner',
                'verbose_name_plural': 'multiple event planners',
            },
            bases=('polls.eventplanner',),
        ),
    ]
