# Generated by Django 5.1.1 on 2024-12-22 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatPage',
            fields=[
                ('flatpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flatpages.flatpage')),
                ('predefined', models.BooleanField(default=False)),
                ('updated', models.BooleanField(default=True)),
            ],
            bases=('flatpages.flatpage',),
        ),
    ]
