# Generated by Django 6.0 on 2026-01-17 17:56

import django.utils.timezone
from django.db import migrations, models


def set_created(apps, schema_editor):
    Comment = apps.get_model("forum", "Comment")
    Message = apps.get_model("forum", "Message")
    for comment in Comment.objects.all():
        comment.created = comment.modified
        comment.save(update_fields=["created"])
    for message in Message.objects.all():
        message.created = message.modified
        message.save(update_fields=["created"])


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_comment_content_alter_message_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['message', 'created'], 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['first_message__created'], 'verbose_name_plural': 'posts'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='date',
            new_name='modified',
        ),
        migrations.AddField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RunPython(set_created),
    ]
