# Generated by Django 5.0.6 on 2024-05-26 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatroom_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={'ordering': ('date_added',), 'verbose_name': 'chat room', 'verbose_name_plural': 'chat rooms'},
        ),
    ]
