# Generated by Django 5.0.6 on 2024-06-01 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='account',
            new_name='member',
        ),
    ]
