# Generated by Django 5.0.7 on 2024-07-31 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chatmessage_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateChatRoom',
            fields=[
                ('chatroom_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.chatroom')),
                ('admins', models.ManyToManyField(blank=True, related_name='group_chat_rooms_admins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'private chat room',
                'verbose_name_plural': 'private chat rooms',
            },
            bases=('chat.chatroom',),
        ),
    ]
