# Generated by Django 6.0.6 on 2026-07-12 09:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_chatmessage_date_modified_chatmessage_read_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_chat_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
