# Generated by Django 6.0.6 on 2026-08-23 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_default_tenant(apps, schema_editor):
  Tenant = apps.get_model("tenants", "Tenant")
  ChatRoom = apps.get_model("chat", "ChatRoom")
  ChatMessage = apps.get_model("chat", "ChatMessage")
  db = schema_editor.connection.alias
  from django.conf import settings

  default = Tenant.objects.using(db).get(slug=settings.DEFAULT_TENANT_SLUG)
  # Legacy rooms/messages land on the default tenant.
  ChatRoom.objects.using(db).filter(tenant__isnull=True).update(tenant=default)
  ChatMessage.objects.using(db).filter(tenant__isnull=True).update(tenant=default)


def unassign_tenant(apps, schema_editor):
  ChatRoom = apps.get_model("chat", "ChatRoom")
  ChatMessage = apps.get_model("chat", "ChatMessage")
  db = schema_editor.connection.alias
  ChatRoom.objects.using(db).update(tenant=None)
  ChatMessage.objects.using(db).update(tenant=None)

class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_chatmessage_read_by'),
        ('tenants', '0003_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='chat_chatme_room_id_95b551_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatroom',
            name='chat_chatro_slug_23d243_idx',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='tenant',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='tenant',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant'),
        ),
        # Backfill the (temporarily nullable) tenant before indexes/constraints.
        migrations.RunPython(assign_default_tenant, reverse_code=unassign_tenant),
        migrations.AlterField(
            model_name='chatroom',
            name='slug',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['tenant', 'room'], name='chat_chatme_tenant__b2a413_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['tenant', 'slug'], name='chat_chatro_tenant__4dc5fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='chat room slugs are unique inside a tenant'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='tenant',
            field=models.ForeignKey(editable=False, null=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='tenant',
            field=models.ForeignKey(editable=False, null=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant'),
        ),
    ]
