# Generated by Django 5.2 on 2025-05-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified_ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiedad',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
