# Generated by Django 5.2.7 on 2025-10-04 10:11

from django.db import migrations, models
from django.utils.html import strip_tags


def set_title(apps, schema_editor):
    """Compute title based on description"""
    model = apps.get_model("troves", "Trove")
    for treasure in model.objects.all():
        descr = strip_tags(treasure.description) if treasure.description else ""
        if descr and treasure.title == "title":
            if len(descr) < 100:
                treasure.title = descr
                treasure.description = None
            else:
                treasure.title = descr[:97] + '...'
        treasure.save()


class Migration(migrations.Migration):

    dependencies = [
        ('troves', '0002_mkdirs'),
    ]

    operations = [
        migrations.AddField(
            model_name='trove',
            name='title',
            field=models.CharField(default='title', verbose_name='Title of the treasure (this will appear in the list)',
                                   max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trove',
            name='description',
            field=models.TextField(blank=True, null=True,
                                   verbose_name='Description of the treasure (this will appear in the details)'),
        ),
        migrations.RunPython(set_title),

    ]
