# Generated by Django 5.2.7 on 2025-11-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troves', '0003_trove_title_alter_trove_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trove',
            name='title',
            field=models.CharField(max_length=110, verbose_name='Title of the treasure (this will appear in the list)'),
        ),
    ]
