# Generated by Django 5.2 on 2025-04-21 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_choiceanswer_answer_question_possible_choices_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPlanner',
            fields=[
                ('poll_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.poll')),
                ('location', models.CharField(blank=True, default='', max_length=250, verbose_name='location')),
                ('chosen_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'event planner',
                'verbose_name_plural': 'event planners',
            },
            bases=('polls.poll',),
        ),
        migrations.CreateModel(
            name='MultiChoiceAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField(blank=True, default=list, verbose_name='choices')),
            ],
            options={
                'verbose_name': 'multiple choice answer',
                'verbose_name_plural': 'multiple choice answers',
            },
        ),
        migrations.CreateModel(
            name='SingleEventAnswer',
            fields=[
                ('choiceanswer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.choiceanswer')),
            ],
            options={
                'verbose_name': 'single event answer',
                'verbose_name_plural': 'single event answers',
            },
            bases=('polls.choiceanswer',),
        ),
        migrations.AlterModelOptions(
            name='choiceanswer',
            options={'verbose_name': 'choice answer', 'verbose_name_plural': 'choice answers'},
        ),
        migrations.AlterModelOptions(
            name='datetimeanswer',
            options={'verbose_name': 'date answer', 'verbose_name_plural': 'date answers'},
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['pub_date'], 'verbose_name': 'poll', 'verbose_name_plural': 'polls'},
        ),
        migrations.AlterModelOptions(
            name='pollanswer',
            options={'verbose_name': 'poll answer', 'verbose_name_plural': 'poll answers'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id'], 'verbose_name': 'question', 'verbose_name_plural': 'questions'},
        ),
        migrations.AlterModelOptions(
            name='textanswer',
            options={'verbose_name': 'text answer', 'verbose_name_plural': 'text answers'},
        ),
        migrations.AlterModelOptions(
            name='yesnoanswer',
            options={'verbose_name': 'yes/no answer', 'verbose_name_plural': 'yes/no answers'},
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('YN', 'Yes/No'), ('SC', 'Single Choice'), ('MC', 'Multiple Choices'), ('OT', 'Open Text'), ('DT', 'Date')], default='YN', max_length=2, verbose_name='Question Type'),
        ),
        migrations.CreateModel(
            name='MultiEventAnswer',
            fields=[
                ('multichoiceanswer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.multichoiceanswer')),
            ],
            options={
                'verbose_name': 'multiple event answer',
                'verbose_name_plural': 'multiple event answers',
            },
            bases=('polls.multichoiceanswer',),
        ),
        migrations.AddField(
            model_name='multichoiceanswer',
            name='poll_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pollanswer'),
        ),
        migrations.AddField(
            model_name='multichoiceanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_%(class)s', to='polls.question'),
        ),
    ]
