# Generated by Django 5.2.8 on 2025-11-21 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
  initial = True

  dependencies = [
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.CreateModel(
      name="Family",
      fields=[
        (
          "id",
          models.BigAutoField(
            auto_created=True,
            primary_key=True,
            serialize=False,
            verbose_name="ID",
          ),
        ),
        (
          "union_type",
          models.CharField(
            choices=[
              ("MARR", "Marriage"),
              ("PACS", "PACS"),
              ("COHA", "Cohabitation"),
              ("OTHE", "Other"),
            ],
            default="MARR",
            max_length=4,
            verbose_name="Union Type",
          ),
        ),
        (
          "union_date",
          models.DateField(blank=True, null=True, verbose_name="Union Date"),
        ),
        (
          "union_place",
          models.CharField(blank=True, max_length=255, verbose_name="Union Place"),
        ),
        (
          "separation_date",
          models.DateField(blank=True, null=True, verbose_name="Separation Date"),
        ),
      ],
      options={
        "verbose_name": "Family",
        "verbose_name_plural": "Families",
      },
    ),
    migrations.CreateModel(
      name="Person",
      fields=[
        (
          "id",
          models.BigAutoField(
            auto_created=True,
            primary_key=True,
            serialize=False,
            verbose_name="ID",
          ),
        ),
        (
          "first_name",
          models.CharField(max_length=150, verbose_name="First Name"),
        ),
        (
          "last_name",
          models.CharField(max_length=150, verbose_name="Last Name"),
        ),
        (
          "sex",
          models.CharField(
            choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
            default="O",
            max_length=1,
            verbose_name="Sex",
          ),
        ),
        (
          "birth_date",
          models.DateField(blank=True, null=True, verbose_name="Birth Date"),
        ),
        (
          "birth_place",
          models.CharField(blank=True, max_length=255, verbose_name="Birth Place"),
        ),
        (
          "death_date",
          models.DateField(blank=True, null=True, verbose_name="Death Date"),
        ),
        (
          "death_place",
          models.CharField(blank=True, max_length=255, verbose_name="Death Place"),
        ),
        ("notes", models.TextField(blank=True, verbose_name="Notes")),
        (
          "gedcom_id",
          models.CharField(
            blank=True,
            max_length=50,
            null=True,
            unique=True,
            verbose_name="GEDCOM ID",
          ),
        ),
        (
          "child_of_family",
          models.ForeignKey(
            blank=True,
            null=True,
            on_delete=django.db.models.deletion.SET_NULL,
            related_name="children",
            to="genealogy.family",
            verbose_name="Child of Family",
          ),
        ),
        (
          "member",
          models.OneToOneField(
            blank=True,
            null=True,
            on_delete=django.db.models.deletion.SET_NULL,
            related_name="genealogy_person",
            to=settings.AUTH_USER_MODEL,
            verbose_name="Linked Member",
          ),
        ),
      ],
      options={
        "verbose_name": "Person",
        "verbose_name_plural": "People",
        "ordering": ["last_name", "first_name"],
      },
    ),
    migrations.AddField(
      model_name="family",
      name="partner1",
      field=models.ForeignKey(
        blank=True,
        null=True,
        on_delete=django.db.models.deletion.CASCADE,
        related_name="unions_as_p1",
        to="genealogy.person",
        verbose_name="Partner 1",
      ),
    ),
    migrations.AddField(
      model_name="family",
      name="partner2",
      field=models.ForeignKey(
        blank=True,
        null=True,
        on_delete=django.db.models.deletion.CASCADE,
        related_name="unions_as_p2",
        to="genealogy.person",
        verbose_name="Partner 2",
      ),
    ),
    migrations.AddIndex(
      model_name="person",
      index=models.Index(fields=["last_name"], name="genealogy_p_last_na_5cd12f_idx"),
    ),
    migrations.AddIndex(
      model_name="person",
      index=models.Index(fields=["birth_date"], name="genealogy_p_birth_d_c5547a_idx"),
    ),
  ]
