# Generated by Django 6.0 on 2025-12-28 18:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='GedCom UUID'),
        ),
        migrations.AlterField(
            model_name='family',
            name='union_type',
            field=models.CharField(choices=[('MARR', 'Marriage'), ('CIVI', 'Civil union'), ('COHA', 'Cohabitation'), ('OTHE', 'Other')], default='MARR', max_length=4, verbose_name='Union Type'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1, verbose_name='Gender'),
        ),
    ]
