# Generated by Django 6.0 on 2025-12-28 19:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0002_person_uid_alter_family_union_type_alter_person_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='GedCom UUID'),
        ),
    ]
