# List of correspondance of icons in https://materialdesignicons.com/
DJANGO_ICONS = {
  # footer icons
  "copyleft": "copyleft",
  # main icons
  "back": "arrow-up-left",
  "delete": "trash-can-outline",
  "edit": "pencil-outline",
  "save": "content-save-outline",
  "details": "eye-outline",
  "submit": "check-circle-outline",
  "create": "checkbox-marked-circle-auto-outline",
  "create-plus": "checkbox-marked-circle-plus-outline",
  "update": "check-underline-circle-outline",
  "cancel": "close-circle-outline",
  "clear": "backspace-outline",
  "new": "plus-box-outline",
  "send-message": "send-variant-outline",
  "search": "magnify",
  "print": "printer",
  "pdf": "file-pdf-box",
  "help": "help-circle-outline",
  "settings": "cog-outline",
  "menu-open": "menu-open",
  "menu-close": "menu-close",
  "information": "information-outline",
  "contact": "card-account-mail-outline",
  "private": "eye-lock-outline",
  "upload": "upload-box-outline",
  "download": "download-box-outline",
  "about": "information-variant",
  "admin": "application-cog-outline",
  "stats": "chart-box-outline",
  "question": "help-box-multiple-outline",
  "leave-group": "account-multiple-minus-outline",
  # arrows
  "arrow-down": "arrow-down-thin",
  "arrow-up": "arrow-up-thin",
  "arrow-up-down": "swap-vertical",
  "menu-right": "menu-right",
  # emoticons
  "thumb-up": "thumb-up-outline",
  "thumb-down": "thumb-down-outline",
  "poop": "emoticon-poop-outline",
  "confused": "robot-confused-outline",
  "cool": "emoticon-cool-outline",
  "wink": "emoticon-wink-outline",
  # auth icons
  "signin": "login",
  "signout": "logout",
  "signup": "account-plus",
  "change-password": "lock-reset",
  # pagination icons
  "pagination-previous": "chevron-left-box-outline",
  "pagination-next": "chevron-right-box-outline",
  # follow icons
  "follow": "link-variant",
  "unfollow": "link-variant-off",
  # member icons
  "member": "account-outline",
  "member-link": "open-in-new",
  "new-member": "account-plus-outline",
  "invite-member": "card-account-mail-outline",
  "invite-request": "account-box-plus-outline",
  "import-members": "account-multiple-plus-outline",
  "activate-member": "account-reactivate",
  "members": "account-group-outline",
  "profile": "account-box-edit-outline",
  "birthday": "cake-variant-outline",
  "birthday-variant": "cake-variant",
  "directory": "format-list-text",
  "directory-variant": "book-alphabet",
  "deceased": "shield-cross-outline",  # or "coffin"?
  "invite": "card-account-mail-outline",
  # gallery icons
  "galleries": "folder-multiple-image",
  "new-gallery": "file-image-plus-outline",
  "edit-gallery": "image-edit",
  "import-galleries": "folder-plus-outline",
  "new-photo": "image-plus-outline",
  "edit-photo": "image-edit-outline",
  # forum icons
  "forum": "forum-outline",
  "new-forum": "forum-plus-outline",
  # chat icons
  "new-chat-room": "chat-plus-outline",
  "chat-room": "chat",
  # page icons
  "page": "page-next",
  "page-level": "page-next-outline",
  "new-page": "book-open-page-variant-outline",
  "edit-page": "note-edit-outline",
  # troves icons
  "new-treasure": "book-plus-outline",
  "edit-treasure": "note-edit-outline",
  "troves": "treasure-chest",
  # polls icons
  "vote": "vote",
  "new-poll": "vote-outline",
  "update-poll": "ballot-recount-outline",
  "poll-choice-question": "checkbox-multiple-marked-circle-outline",
  "poll-multiple-choice-question": "checkbox-multiple-marked-outline",
  "poll-yesno-question": "checkbox-marked-circle-outline",
  "poll-open-text-question": "text-box-outline",
  "poll-date-time-question": "calendar-clock",
  # events icons
  "new-event": "calendar-plus",
  # classified ads icons
  "new-classified-ad": "file-plus-outline",
  "edit-classified-ad": "file-edit-outline",
  "classified-ads": "file-document-multiple",
  "classified-ad": "file-document",
  "camera": "camera",
  # genealogy icons
  "family-tree": "family-tree",
  "statistics": "chart-pie",
  "dashboard": "monitor-dashboard",
  "gender-male": "gender-male",
  "gender-female": "gender-female",
  "genderless": "gender-non-binary",
}
