# Generated by Django 5.0.2 on 2024-03-30 15:31

import django.db.models.deletion
import pathlib
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_and_street', models.CharField(max_length=120, verbose_name='Number & Street name')),
                ('complementary_info', models.CharField(blank=True, default='', max_length=120, verbose_name='Complementary info')),
                ('zip_code', models.CharField(max_length=12, verbose_name='Zip code')),
                ('city', models.CharField(max_length=120, verbose_name='City')),
                ('country', models.CharField(max_length=32, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=72, verbose_name='Name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.family', verbose_name='Parent family')),
            ],
            options={
                'verbose_name': 'family',
                'verbose_name_plural': 'families',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='default.jpg', upload_to=pathlib.PurePosixPath('/home/olivi/devt/cousinsmatter/media/avatars'))),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Phone')),
                ('birthdate', models.DateField(null=True, verbose_name='Birthdate')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Linked Account')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='members.address', verbose_name='Address')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.family', verbose_name='Family')),
                ('managing_account', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='managing_account', to=settings.AUTH_USER_MODEL, verbose_name='Managing account')),
            ],
            options={
                'verbose_name': 'member',
                'verbose_name_plural': 'members',
            },
        ),
    ]
