# Generated by Django 5.0.2 on 2024-02-19 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_number', models.CharField(max_length=12)),
                ('street', models.CharField(max_length=120)),
                ('complementary_info', models.CharField(max_length=120)),
                ('zip_code', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=72)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.family')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('cell_phone', models.CharField(blank=True, max_length=32)),
                ('alternate_phone', models.CharField(blank=True, max_length=32)),
                ('birthdate', models.DateField()),
                ('personal_email', models.EmailField(blank=True, max_length=254)),
                ('alternate_email', models.EmailField(blank=True, max_length=254)),
                ('avatar', models.ImageField(blank=True, upload_to='')),
                ('website', models.URLField(blank=True)),
                ('address', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='members.address')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.family')),
            ],
        ),
    ]
