# Generated by Django 5.0.2 on 2024-04-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='avatars'),
        ),
    ]
