# Generated by Django 5.0.2 on 2024-02-19 15:59

import members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=members.models.Member.family_directory_path),
        ),
    ]
