# Generated by Django 5.0.2 on 2024-04-11 08:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['city', 'zip_code', 'number_and_street'], 'verbose_name': 'address', 'verbose_name_plural': 'addresses'},
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ['name'], 'verbose_name': 'family', 'verbose_name_plural': 'families'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['account__last_name', 'account__first_name'], 'verbose_name': 'member', 'verbose_name_plural': 'members'},
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['city', 'zip_code'], name='members_add_city_8915c5_idx'),
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['name'], name='members_fam_name_9e8e97_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['account', 'birthdate'], name='members_mem_account_69df0e_idx'),
        ),
    ]
