# Generated by Django 5.0.6 on 2024-06-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0003_member_privacy_consent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="privacy_consent",
            field=models.BooleanField(default=False, verbose_name="Privacy consent"),
        ),
    ]
