# Generated by Django 5.0.2 on 2024-03-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_address_options_alter_family_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='complementary_info',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Complementary info'),
        ),
        migrations.AlterField(
            model_name='member',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Birthdate'),
        ),
    ]
