# Generated by Django 5.0.2 on 2024-05-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_member_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birthdate',
            field=models.DateField(help_text='Click on the month name or the year to change them quickly', null=True, verbose_name='Birthdate'),
        ),
    ]
