# Generated by Django 5.0.6 on 2024-05-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_member_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='description',
            field=models.TextField(blank=True, help_text='Describe yourself, what you like or dislike...', max_length=2097152, null=True, verbose_name='Who I am'),
        ),
        migrations.AddField(
            model_name='member',
            name='hobbies',
            field=models.JSONField(blank=True, help_text='Provide a list of short hobbies descriptions', null=True, verbose_name='My hobbies'),
        ),
    ]
