# Generated by Django 5.0.6 on 2024-05-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_member_description_member_hobbies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='hobbies',
            field=models.CharField(blank=True, help_text='Provide a list of hobbies separated by commas', max_length=256, null=True, verbose_name='My hobbies'),
        ),
    ]
