# Generated by Django 5.2.6 on 2025-09-12 12:14

from django.db import migrations, models, connection
from cm_main.utils import remove_accents


def init_unaccent_fields(apps, schema_editor):
    match connection.vendor:
        case 'postgresql':
            # Register unaccent extension in the database
            schema_editor.execute("CREATE EXTENSION IF NOT EXISTS unaccent;")
        case 'sqlite':
            # Register unaccent custom function in the database, same name as pg extension
            connection.cursor().connection.create_function('unaccent', 1, remove_accents)
    # update unaccent fields
    schema_editor.execute("UPDATE members_member SET "
                          "first_name_unaccent = lower(unaccent(first_name)), "
                          "last_name_unaccent = lower(unaccent(last_name));")


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('members', '0009_logintrace'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='first_name_unaccent',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='last_name_unaccent',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['first_name_unaccent'], name='members_mem_first_n_feb60f_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['last_name_unaccent'], name='members_mem_last_na_79ca5b_idx'),
        ),
        migrations.RunPython(init_unaccent_fields),
    ]
