# Generated by Django 6.0.3 on 2026-04-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_alter_address_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email_batch_frequency',
            field=models.CharField(choices=[('never', 'Never'), ('immediate', 'Immediately'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='immediate', max_length=10, verbose_name='Email frequency'),
        ),
    ]
