# Generated by Django 6.0.4 on 2026-04-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_member_email_batch_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email_batch_frequency',
            field=models.CharField(choices=[('never', 'Never'), ('immediate', 'Immediately'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='immediate', help_text='How often you want to receive email notifications about the followed elements (members, chat messages, etc.)', max_length=10, verbose_name='Email frequency'),
        ),
    ]
