# Generated by Django 6.0.6 on 2026-07-12 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_remove_unaccent_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='self', to='members.family', verbose_name='Parent family'),
        ),
    ]
