# Generated by Django 6.0.8 on 2026-08-08 16:36

import django.contrib.auth.validators
import django.db.models.deletion
from django.db import migrations, models


def assign_tenants(apps, schema_editor):
  from django.conf import settings

  Tenant = apps.get_model("tenants", "Tenant")
  Member = apps.get_model("members", "Member")
  db_alias = schema_editor.connection.alias
  system_tenant = Tenant.objects.using(db_alias).get(slug=settings.SYSTEM_TENANT_SLUG)
  default_tenant = Tenant.objects.using(db_alias).get(slug=settings.DEFAULT_TENANT_SLUG)
  # Platform superusers belong to the system (cross-tenant) tenant.
  Member.objects.using(db_alias).filter(is_superuser=True).update(tenant=system_tenant)
  # Legacy data and every other member land on the default tenant.
  Member.objects.using(db_alias).filter(tenant__isnull=True).update(tenant=default_tenant)


def unassign_tenants(apps, schema_editor):
  Member = apps.get_model("members", "Member")
  db_alias = schema_editor.connection.alias
  Member.objects.using(db_alias).update(tenant=None)


class Migration(migrations.Migration):
  dependencies = [
    ("auth", "0012_alter_user_first_name_max_length"),
    ("members", "0016_alter_family_parent"),
    ("tenants", "0002_seed_tenants"),
  ]

  operations = [
    migrations.AddField(
      model_name="member",
      name="role",
      field=models.CharField(
        choices=[("member", "Member"), ("admin", "Tenant admin")], default="member", max_length=16, verbose_name="Role"
      ),
    ),
    migrations.AddField(
      model_name="member",
      name="tenant",
      field=models.ForeignKey(
        editable=False,
        null=True,
        on_delete=django.db.models.deletion.PROTECT,
        related_name="members",
        to="tenants.tenant",
        verbose_name="Tenant",
      ),
    ),
    # Backfill the (temporarily nullable) tenant before it becomes non-null and
    # before the (tenant, username) constraint is enforced.
    migrations.RunPython(assign_tenants, reverse_code=unassign_tenants),
    migrations.AlterField(
      model_name="member",
      name="username",
      field=models.CharField(
        error_messages={"unique": "A user with that username already exists."},
        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
        max_length=150,
        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
        verbose_name="username",
      ),
    ),
    migrations.AddIndex(
      model_name="member",
      index=models.Index(fields=["tenant", "last_name", "first_name"], name="members_mem_tenant__51e504_idx"),
    ),
    migrations.AddConstraint(
      model_name="member",
      constraint=models.UniqueConstraint(fields=("tenant", "username"), name="member_tenant_username_uniq"),
    ),
    migrations.AlterField(
      model_name="member",
      name="tenant",
      field=models.ForeignKey(
        editable=False,
        on_delete=django.db.models.deletion.PROTECT,
        related_name="members",
        to="tenants.tenant",
        verbose_name="Tenant",
      ),
    ),
  ]
