# Creates a multiplatform image of cousins matter and push it to ghcr.io for each new release
# This callable workflows needs the following params: see inputs below

name: Image Build & Push

on:   
  workflow_call:

    inputs:

      push:
        description: 'Should the built image be pushed to the registry?'
        required: true
        type: boolean

      platforms:
        description: 'a list of platform architecture to be built in the image.'
        required: false
        type: string
        default: linux/amd64,linux/arm64

      registry:
        description: 'The registry where the image will be pushed.'
        required: false
        type: string
        default: ghcr.io

      username:
        description: 'The user name to log in the registry. If not provide, uses the github actor'
        required: false
        type: string
        default: ${{ github.actor }}

      image:
        description: 'the name of the image to be built'
        required: false
        type: string
        default: ${{ github.repository }}

      tags:
        description: 'list of tags of the image to be built. If not provided, computed automatically based on the version'
        required: false
        type: string
        default: ''

      labels:
        description: 'list of labels of the image to be built. If not provided, computed automatically based on the version'
        required: false
        type: string
        default: ''

    secrets:
      
      password:
        description: 'The password to log in the registry. If not provided, will use the GITHUB_TOKEN'
        required: false

env:
  TAGS_DEF: ${{ github.event_name == 'release' && 'type=semver,pattern={{version}}' || github.event_name == 'push' && 'type=ref,event=branch' || 'type=sha' }}
  
jobs:
  test-build-image-publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 tblib
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0.3
        with:
          envkey_SECRET_KEY: 'django-insecure-this-is-just-for-test'
          envkey_SITE_NAME: 'My Beautiful Site'
          envkey_ALLOWED_HOSTS: '127.0.0.1,localhost'
          envkey_LANGUAGE_CODE: 'fr-FR'
          envkey_EMAIL_HOST: 'smtp.gmail.com'
          envkey_EMAIL_PORT: 465
          envkey_EMAIL_HOST_USER: 'nobody@gmail.com'
          envkey_EMAIL_HOST_PASSWORD: 'no matter'
          directory: .
          file_name: .env
          fail_on_empty: false
          sort_keys: false

      - name: Test django
        run: |
          python ./manage.py test --parallel
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR.io
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.username }}
          password: ${{ secrets.password || secrets.GITHUB_TOKEN }}
          registry: ${{ inputs.registry }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        if: ${{ inputs.tags == '' }}
        with:
          images: ${{ inputs.registry }}/${{ inputs.image}}
          tags: ${{ env.TAGS_DEF }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ inputs.platforms}}
          push: ${{ inputs.push }}
          tags: ${{ inputs.tags || steps.meta.outputs.tags }}
          labels: ${{ inputs.labels || steps.meta.outputs.labels }}

      - name: Test Docker Image
        env:
          SOCKS_MOUNT: -v "/var/run/docker.sock":"/var/run/docker.sock"
          MOUNTS: -v ./data:/app/data -v ./.env:/app/.env -v ./media:/app/media
        run: |
          ls -l /var/run/docker.sock
          mkdir -p ./data ./media
          docker run $MOUNTS ${{ inputs.tags || steps.meta.outputs.tags }} python manage.py test --parallel


