# Creates a multiplatform image of cousins matter and push it to ghcr.io for each new release
# This callable workflows needs the following params: see inputs below

name: Image Build & Push

on:   
  workflow_call:

    inputs:

      push:
        description: 'Should the built image be pushed to the registry?'
        required: true
        type: boolean

      platforms:
        description: 'a list of platform architecture to be built in the image.'
        required: false
        type: string
        default: linux/amd64,linux/arm64

      registry:
        description: 'The registry where the image will be pushed.'
        required: false
        type: string
        default: ghcr.io

      username:
        description: 'The user name to log in the registry. If not provide, uses the github actor'
        required: false
        type: string
        default: ${{ github.actor }}

      image:
        description: 'the name of the image to be built'
        required: false
        type: string
        default: ${{ github.repository }}

      tags:
        description: 'list of tags of the image to be built. If not provided, computed automatically based on the version'
        required: false
        type: string
        default: ''

      labels:
        description: 'list of labels of the image to be built. If not provided, computed automatically based on the version'
        required: false
        type: string
        default: ''

    secrets:
      
      password:
        description: 'The password to log in the registry. If not provided, will use the GITHUB_TOKEN'
        required: false

env:
  TAGS_DEF: ${{ github.event == 'release' && 'type=semver,pattern={{version}}' || github.event == 'push' && 'type=pep440,pattern={{version}}' || 'type=edge' }}
  
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR.io
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.username }}
          password: ${{ secrets.password || secrets.GITHUB_TOKEN }}
          registry: ${{ inputs.registry }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        if: ${{ inputs.tags == '' }}
        with:
          images: ${{ inputs.registry }}/${{ inputs.image}}
          tags: ${{ env.TAGS_DEF }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ inputs.platforms}}
          push: ${{ inputs.push }}
          tags: ${{ inputs.tags || steps.meta.outputs.tags }}
          labels: ${{ inputs.labels || steps.meta.outputs.labels }}
