# creates a multiplatform image of cousins matter and push it to ghcr.io for each new published release
name: Release build

on:
  release:
    types: [prereleased, published]

jobs:
  build-and-publish:
    uses: leolivier/cousins-matter/.github/workflows/build-and-publish-image-reusable.yml@main
    with:
      push: true
      trace_event: ${{ toJson(github.event) }}
