# creates a multiplatform image of cousins matter and push it to ghcr.io for each new push
name: Push build

on: [push]

jobs:
  test-build-and-push:
    uses: leolivier/cousins-matter/.github/workflows/build-and-publish-image-reusable.yml@main
    with:
      push: true
      trace_event: ${{ toJson(github.event) }}
