# creates a multiplatform image of cousins matter and push it to ghcr.io for each new published release
name: Release build

on:
  release:
    types: [prereleased, published]
  workflow_dispatch: 

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
  
    - name: Configure Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Update release.txt and create/update tag
      run: |
        # Update release.txt
        echo "${{ github.ref_name }}" > release.txt
        git add release.txt
        git commit -m "Update release.txt to version ${{ github.ref_name }}"

        # Attempt to create the tag
        if git push origin HEAD:refs/tags/${{ github.ref_name }}; then
          echo "Tag created successfully"
        else
          echo "Tag already exists, updating it"
          git push origin :refs/tags/${{ github.ref_name }} || true
          git push origin HEAD:refs/tags/${{ github.ref_name }}
        fi

        # Push changes to the current branch
        git push origin HEAD:${{ github.ref_name }}

  check-repository:
    needs: update-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      
      - name: Fetch latest changes
        run: |
          git fetch --all --tags
          git checkout ${{ github.ref }}
          git pull origin ${{ github.ref }}
      
      - name: Debug - Check release.txt content
        run: |
          echo "Current directory: $(pwd)"
          echo "release.txt content:"
          cat release.txt
          echo "Git status:"
          git status
          echo "Latest commit:"
          git log -1

  build-and-publish:
    needs: [update-version, check-repository]
    uses: leolivier/cousins-matter/.github/workflows/build-and-publish-image-reusable.yml@main
    with:
      push: true
      trace_event: ${{ toJson(github.event) }}
      version: ${{ github.event.release.tag_name }}
