# creates a multiplatform image of cousins matter and push it to ghcr.io for each new published release
name: Release build

on:
  release:
    types: [prereleased, published]
  workflow_dispatch: 

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Checkout the branch
      run: |
        # Fetch all branches and tags
        git fetch --all
        # Checkout the branch that triggered the release
        git checkout ${{ github.ref_name }}

    - name: Update release.txt
      run: |
        echo "${{ github.event.release.tag_name }}" > release.txt
        echo -n "release.txt contains: "
        cat release.txt
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add release.txt
        git commit -m "Update release.txt to version ${{ github.event.release.tag_name }}"
        git push origin HEAD:${{ github.ref_name }}

  build-and-publish:
    needs: update-version
    uses: leolivier/cousins-matter/.github/workflows/build-and-publish-image-reusable.yml@main
    with:
      push: true
      trace_event: ${{ toJson(github.event) }}
      version: ${{ github.event.release.tag_name }}
