# creates a multiplatform image of cousins matter and push it to ghcr.io for each new release
name: Release build

on: [push]

jobs:
  run-tests:
    uses: leolivier/cousins-matter/.github/workflows/run-tests-reusable.yml@main
  
  build-and-push:
    uses: leolivier/cousins-matter/.github/workflows/build-and-publish-image-reusable.yml@main
    with:
      push: true
      # tags: $${{github.sha}}
