# Reusable workflow to run test suite with S3 media backend configured.
name: Reusable Test S3

on:
  workflow_call:

jobs:
  test-s3:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      S3_MEDIA_STORAGE_OPTIONS: '{\"access_key\":\"${{ secrets.ACCESS_KEY }}\",\"secret_key\":\"${{ secrets.SECRET_KEY }}\",\"bucket_name\":\"${{ secrets.BUCKET_NAME }}\",\"endpoint_url\":\"https://${{ secrets.ACCOUNT_ID }}.r2.cloudflarestorage.com\"}'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Download test Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: test-docker-image
          path: /tmp

      - name: Load test Docker image
        run: |
          docker load < /tmp/test-image.tar.gz

      - name: Write .env
        run: |
          cp .github/workflows/test.env $GITHUB_WORKSPACE/.env
          echo "COUSINS_MATTER_IMAGE=ghcr.io/${{ github.repository }}:test-${{ github.sha }}" >> $GITHUB_WORKSPACE/.env

      - name: Test Docker Image using S3 backend
        run: |
          python ./scripts/manage_cousins_matter.py install -e -n -d "$GITHUB_WORKSPACE"
          # start tests with S3 variables in .env
          echo 'MEDIA_STORAGE=storages.backends.s3.S3Storage' >> $GITHUB_WORKSPACE/.env
          echo "MEDIA_STORAGE_OPTIONS='${{ env.S3_MEDIA_STORAGE_OPTIONS }}'" >> $GITHUB_WORKSPACE/.env
          cat $GITHUB_WORKSPACE/.env
          # need to install playwright just because of test import error :/
          docker exec cousins-matter python -m pip install -r requirements-dev.txt
          # Ensure containers are stopped before starting fresh
          docker compose -f docker-compose.yml down -v || true
          # Start containers and wait for them to be ready
          docker compose -f docker-compose.yml up -d --wait --wait-timeout 30
          # Verify container exists before running tests just in case
          docker ps | grep cousins-matter || (docker ps && exit 1)
          docker exec cousins-matter python manage.py test --failfast --exclude-tag=ui

      - name: Show docker-compose services logs on failure
        if: failure()
        run: |
          cat $GITHUB_WORKSPACE/.env
          docker ps
          echo "====================cousins-matter================================"
          docker logs cousins-matter
          echo "====================cousins-matter.qcluster======================="
          docker logs cousins-matter.qcluster
          echo "====================cousins-matter.db============================="
          docker logs cousins-matter.db
